[program:fm-mimicgen-wandb-gaussian]
directory=/workspace/fm_dno
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/fm-mimicgen-wandb-gaussian.sh
autostart=false
autorestart=unexpected
startsecs=5
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
