[program:fm-noise-compare-heading-gaussian-dit]
directory=/workspace/fm_dno
environment=PROC_NAME="%(program_name)s"
command=/workspace/fm_dno/scripts/supervisor/fm-noise-compare-heading-gaussian-dit.sh
autostart=false
autorestart=false
startsecs=3
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=60
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
