[program:fm-starvla-heading-wandb]
directory=/workspace/fm_dno
environment=PROC_NAME="%(program_name)s"
command=/workspace/fm_dno/scripts/supervisor/fm-starvla-heading-wandb.sh
autostart=false
autorestart=unexpected
startsecs=10
startretries=5
stopasgroup=false
killasgroup=true
stopsignal=TERM
stopwaitsecs=60
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
