[program:fm-starvla-heading-experiment]
directory=/workspace/fm_dno
environment=PROC_NAME="%(program_name)s"
command=/workspace/fm_dno/scripts/supervisor/fm-starvla-heading-experiment.sh
autostart=false
autorestart=false
startsecs=10
stopasgroup=false
killasgroup=true
stopsignal=TERM
stopwaitsecs=960
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
