[program:fm-starvla-heading-profile]
directory=/workspace/fm_dno
environment=PROC_NAME="%(program_name)s"
command=/workspace/fm_dno/scripts/supervisor/fm-starvla-heading-profile.sh
autostart=false
autorestart=false
startsecs=10
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=300
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
